services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taku_vault_development
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

volumes:
  db-data:
  bundle:
