services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB は「初期作成用」なので dev でも良いが、test は Rails 側で作れる前提にする
      POSTGRES_DB: taku_vault_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"

    environment:
      RAILS_ENV: development
      RACK_ENV: development
      APP_HOST: localhost:3000
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      CHROME_BIN: /usr/bin/chromium
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    depends_on:
      db:
        condition: service_healthy
    init: true

  worker:
    profiles: ["jobs"]
    build: .
    command: bin/jobs start
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      RACK_ENV: ${RACK_ENV:-development}
      APP_HOST: ${APP_HOST:-localhost:3000}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    depends_on:
      db:
        condition: service_healthy
    init: true



volumes:
  pg_data:
  bundle:
